spring:
  application:
    name: currency-exchange
server:
  port: '8000'
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  sleuth:
    sampler:
      probability: '1.0'
      
      resilience4j:
  retry:
    instances:
      sample-api:
        waitDuration: 3s
        enableExponentialBackoff: 'true'
        maxAttempts: '5'
