# server:
#   port: 8080
  
# spring:
#   cloud:
#     consul:
#       discovery:
#         instanceId: ServiceA
#         health-check-interval: 5s
#       config:
#         management: 
#           enabled: true
#     stream:
#       bindings:
#         output:
#           binder: kafka
#           destination: cloudEX
# management:
#   security: 
#     enabled: false

spring:
  application:
    name: spring-cloud-config-server

    
limits-service:
  minimum: '3'
  maximum: '996'
